# ===============================================================
# NexT 主题自定义配置
# ===============================================================

# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------

custom_file_path:
  style: source/_data/styles.styl

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

scheme: Gemini

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# 在文章底部显示版权信息
creative_commons:
  license: by-nc-sa
  sidebar: false
  post: true
  language: deed.zh

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  CO 讨论区精华: /co-discussions/ || fa fa-comment
  OS 讨论区精华: /os-discussions/ || fa fa-comment

# ---------------------------------------------------------------
# Math Formulas Render Support
# ---------------------------------------------------------------

math:
  mathjax:
    enable: true

# ---------------------------------------------------------------
# Comments Settings
# ---------------------------------------------------------------

comments:
  active: gitalk

gitalk:
  enable: true
  github_id: TripleCamera
  repo: triplecamera.github.io
  client_id: 8e3318b060ee959cacec
  client_secret: 3a6c863d9640cee4d16dc8e59c8053fa56d7591b
  admin_user: TripleCamera
  language: zh-CN
